name: Deploy Python Image to ECR

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - uses: actions/checkout@v2
    - name: Build python image
      run: |
        cd docker/python
        docker build -t airflow-python-container:latest .


    - name: Tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: airflow-python-container
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag airflow-python-container:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    # build: 
    #   steps:
    #   - uses: actions/checkout@v2
    #   - name: Docker Authentication
    #     env:
    #       DOCKER_USER: ${{secrets.DOCKER_USER}}
    #       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #     run: |
    #       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    #   - name: Docker Build Python Image
    #     run: |
    #       cd docker/python
    #       docker build -t ${{secrets.DOCKER_USER}}/airflow-python-container:dev-latest .
      
    #   - name: Docker Push Python Image
    #     run: docker push ${{secrets.DOCKER_USER}}/airflow-python-container:dev-latest
